export const ERROR_CODE_INTERNAL_SERVER_ERROR = 500;
export const ERROR_CODE_NOT_FOUND = 404;
export const ERROR_CODE_BAD_REQUEST = 400;
export const CREATED_CODE = 201;
export const ERROR_CODE_UNAUTHORIZED = 401;
export const CONFLICT_ERROR = 409;
